// Auto-generated by tools/build_vocab.py from data/worksheet{1,2}.docx
// plus any data/extra/*.tsv. Hansol's Chinese vocabulary. Do not edit by hand.
window.VOCAB = [
  {
    "id": 1,
    "hanzi": "亲戚",
    "pinyin": "qīn qi",
    "meaning": "친척",
    "kr": "우리는 명절에 친척들과 자주 만납니다.",
    "cn_sentence": "我们在节日里经常和亲戚们见面。",
    "cn_pinyin": "Wǒ men zài jié rì li jīng cháng hé qīn qi men jiàn miàn.",
    "theme": "family"
  },
  {
    "id": 2,
    "hanzi": "圣诞节",
    "pinyin": "Shèng dàn jié",
    "meaning": "크리스마스",
    "kr": "크리스마스에 친구들과 파티를 해요.",
    "cn_sentence": "圣诞节和朋友们开派对。",
    "cn_pinyin": "Shèng dàn jié hé péng you men kāi pài duì.",
    "theme": "time"
  },
  {
    "id": 3,
    "hanzi": "领带",
    "pinyin": "lǐng dài",
    "meaning": "넥타이",
    "kr": "넥타이를 매야 해요.",
    "cn_sentence": "需要系领带。",
    "cn_pinyin": "Xū yào jì lǐng dài.",
    "theme": "clothing"
  },
  {
    "id": 4,
    "hanzi": "皮带",
    "pinyin": "pí dài",
    "meaning": "벨트",
    "kr": "벨트를 채야 바지가 안 흘러내려요.",
    "cn_sentence": "系上皮带裤子才不会掉。",
    "cn_pinyin": "Jì shàng pí dài kù zi cái bú huì diào.",
    "theme": "clothing"
  },
  {
    "id": 5,
    "hanzi": "皮鞋",
    "pinyin": "pí xié",
    "meaning": "구두",
    "kr": "구두를 닦았어요.",
    "cn_sentence": "擦了皮鞋。",
    "cn_pinyin": "Cā le pí xié.",
    "theme": "clothing"
  },
  {
    "id": 6,
    "hanzi": "连衣裙",
    "pinyin": "lián yī qún",
    "meaning": "원피스",
    "kr": "원피스가 예쁘네요.",
    "cn_sentence": "连衣裙真漂亮。",
    "cn_pinyin": "Lián yī qún zhēn piào liang.",
    "theme": "clothing"
  },
  {
    "id": 7,
    "hanzi": "套装",
    "pinyin": "tào zhuāng",
    "meaning": "정장 세트",
    "kr": "정장 세트를 샀어요.",
    "cn_sentence": "买了套装。",
    "cn_pinyin": "Mǎi le tào zhuāng.",
    "theme": "clothing"
  },
  {
    "id": 8,
    "hanzi": "袜子",
    "pinyin": "wà zi",
    "meaning": "양말",
    "kr": "양말을 신어야 해요.",
    "cn_sentence": "要穿袜子。",
    "cn_pinyin": "Yào chuān wà zi.",
    "theme": "clothing"
  },
  {
    "id": 9,
    "hanzi": "经理",
    "pinyin": "jīng lǐ",
    "meaning": "경리·매니저",
    "kr": "경리님께 보고했어요.",
    "cn_sentence": "向经理报告了。",
    "cn_pinyin": "Xiàng jīng lǐ bào gào le.",
    "theme": "other"
  },
  {
    "id": 10,
    "hanzi": "公司",
    "pinyin": "gōng sī",
    "meaning": "회사",
    "kr": "회사에 출근하고 있어요.",
    "cn_sentence": "正在去公司上班。",
    "cn_pinyin": "Zhèng zài qù gōng sī shàng bān.",
    "theme": "facilities"
  },
  {
    "id": 11,
    "hanzi": "戴",
    "pinyin": "dài",
    "meaning": "(안경·모자를) 쓰다",
    "kr": "안경을 써야 잘 보여요.",
    "cn_sentence": "戴上眼镜才能看清楚。",
    "cn_pinyin": "Dài shàng yǎn jìng cái néng kàn qīng chu.",
    "theme": "clothing"
  },
  {
    "id": 12,
    "hanzi": "过",
    "pinyin": "guò",
    "meaning": "(명절을) 지내다",
    "kr": "설날을 가족과 함께 보냈습니다.",
    "cn_sentence": "和家人一起过了春节。",
    "cn_pinyin": "Hé jiā rén yì qǐ guò le Chūn jié.",
    "theme": "time"
  },
  {
    "id": 13,
    "hanzi": "忙",
    "pinyin": "máng",
    "meaning": "바쁘다",
    "kr": "요즘 일이 너무 바빠요.",
    "cn_sentence": "最近工作很忙。",
    "cn_pinyin": "Zuì jìn gōng zuò hěn máng.",
    "theme": "other"
  },
  {
    "id": 14,
    "hanzi": "出差",
    "pinyin": "chū chāi",
    "meaning": "출장",
    "kr": "다음 주에 출장을 가요.",
    "cn_sentence": "下周要出差。",
    "cn_pinyin": "Xià zhōu yào chū chāi.",
    "theme": "other"
  },
  {
    "id": 15,
    "hanzi": "律师行",
    "pinyin": "lǜ shī háng",
    "meaning": "변호사 사무실",
    "kr": "그는 변호사 사무실에서 일해요.",
    "cn_sentence": "他在律师行工作。",
    "cn_pinyin": "Tā zài lǜ shī háng gōng zuò.",
    "theme": "facilities"
  },
  {
    "id": 16,
    "hanzi": "外公",
    "pinyin": "wài gōng",
    "meaning": "외할아버지",
    "kr": "외할아버지는 고향에 사십니다.",
    "cn_sentence": "外公住在老家。",
    "cn_pinyin": "Wài gōng zhù zài lǎo jiā.",
    "theme": "family"
  },
  {
    "id": 17,
    "hanzi": "外婆",
    "pinyin": "wài pó",
    "meaning": "외할머니",
    "kr": "외할머니가 예쁜 인형을 사 주셨어요.",
    "cn_sentence": "外婆买了一个漂亮的娃娃给我。",
    "cn_pinyin": "Wài pó mǎi le yí ge piào liang de wá wa gěi wǒ.",
    "theme": "family"
  },
  {
    "id": 18,
    "hanzi": "前年",
    "pinyin": "qián nián",
    "meaning": "재작년",
    "kr": "저는 전년에 한국에 갔었어요.",
    "cn_sentence": "我前年去了一趟韩国。",
    "cn_pinyin": "Wǒ qián nián qù le yí tàng Hán guó.",
    "theme": "time"
  },
  {
    "id": 19,
    "hanzi": "去世",
    "pinyin": "qù shì",
    "meaning": "돌아가시다",
    "kr": "할머니는 작년에 돌아가셨어요.",
    "cn_sentence": "奶奶去年去世了。",
    "cn_pinyin": "Nǎi nai qù nián qù shì le.",
    "theme": "time"
  },
  {
    "id": 20,
    "hanzi": "阿姨",
    "pinyin": "ā yí",
    "meaning": "이모·아주머니",
    "kr": "아이가 이모를 보고 반가워했어요.",
    "cn_sentence": "孩子看到阿姨很高兴。",
    "cn_pinyin": "Hái zi kàn dào ā yí hěn gāo xìng.",
    "theme": "family"
  },
  {
    "id": 21,
    "hanzi": "姨妈",
    "pinyin": "yí mā",
    "meaning": "이모",
    "kr": "우리 이모님은 요리를 잘하세요.",
    "cn_sentence": "我的姨妈很会做饭。",
    "cn_pinyin": "Wǒ de yí mā hěn huì zuò fàn.",
    "theme": "family"
  },
  {
    "id": 22,
    "hanzi": "舅舅",
    "pinyin": "jiù jiu",
    "meaning": "외삼촌",
    "kr": "외삼촌이 저에게 재미있는 이야기를 해 주셨어요.",
    "cn_sentence": "舅舅给我讲了一个有趣的故事。",
    "cn_pinyin": "Jiù jiu gěi wǒ jiǎng le yí ge yǒu qù de gù shi.",
    "theme": "family"
  },
  {
    "id": 23,
    "hanzi": "孩子",
    "pinyin": "hái zi",
    "meaning": "아이",
    "kr": "아이들이 공원에서 놀고 있어요.",
    "cn_sentence": "孩子们在公园里玩。",
    "cn_pinyin": "Hái zi men zài gōng yuán li wán.",
    "theme": "family"
  },
  {
    "id": 24,
    "hanzi": "校长",
    "pinyin": "xiào zhǎng",
    "meaning": "교장",
    "kr": "교장 선생님께서 말씀하셨어요.",
    "cn_sentence": "校长讲话了。",
    "cn_pinyin": "Xiào zhǎng jiǎng huà le.",
    "theme": "facilities"
  },
  {
    "id": 25,
    "hanzi": "办公室",
    "pinyin": "bàn gōng shì",
    "meaning": "사무실",
    "kr": "사무실에 들어가도 돼요?",
    "cn_sentence": "可以进办公室吗？",
    "cn_pinyin": "Kě yǐ jìn bàn gōng shì ma?",
    "theme": "facilities"
  },
  {
    "id": 26,
    "hanzi": "教师",
    "pinyin": "jiào shī",
    "meaning": "교사",
    "kr": "선생님이 질문에 답했어요.",
    "cn_sentence": "老师回答了问题。",
    "cn_pinyin": "Lǎo shī huí dá le wèn tí.",
    "theme": "facilities"
  },
  {
    "id": 27,
    "hanzi": "校医室",
    "pinyin": "xiào yī shì",
    "meaning": "보건실",
    "kr": "아파서 보건실에 갔어요.",
    "cn_sentence": "因为生病去了校医室。",
    "cn_pinyin": "Yīn wèi shēng bìng qù le xiào yī shì.",
    "theme": "facilities"
  },
  {
    "id": 28,
    "hanzi": "中间",
    "pinyin": "zhōng jiān",
    "meaning": "가운데",
    "kr": "가운데에 앉으세요.",
    "cn_sentence": "请坐在中间。",
    "cn_pinyin": "Qǐng zuò zài zhōng jiān.",
    "theme": "directions"
  },
  {
    "id": 29,
    "hanzi": "上面",
    "pinyin": "shàng miàn",
    "meaning": "위쪽",
    "kr": "책상 위에 책이 있어요.",
    "cn_sentence": "桌子上面有书。",
    "cn_pinyin": "Zhuō zi shàng miàn yǒu shū.",
    "theme": "directions"
  },
  {
    "id": 30,
    "hanzi": "下面",
    "pinyin": "xià miàn",
    "meaning": "아래쪽",
    "kr": "의자 아래에 고양이가 있어요.",
    "cn_sentence": "椅子下面有猫。",
    "cn_pinyin": "Yǐ zi xià miàn yǒu māo.",
    "theme": "directions"
  },
  {
    "id": 31,
    "hanzi": "爷爷",
    "pinyin": "yé ye",
    "meaning": "할아버지",
    "kr": "할아버지는 매일 아침 산책을 하십니다.",
    "cn_sentence": "爷爷每天早上散步。",
    "cn_pinyin": "Yé ye měi tiān zǎo shang sàn bù.",
    "theme": "family"
  },
  {
    "id": 32,
    "hanzi": "女儿",
    "pinyin": "nǚ ér",
    "meaning": "딸",
    "kr": "제 딸은 피아노를 잘 칩니다.",
    "cn_sentence": "我的女儿钢琴弹得很好。",
    "cn_pinyin": "Wǒ de nǚ ér gāng qín tán de hěn hǎo.",
    "theme": "family"
  },
  {
    "id": 33,
    "hanzi": "前面",
    "pinyin": "qián miàn",
    "meaning": "앞쪽",
    "kr": "학교 앞에 버스 정류장이 있어요.",
    "cn_sentence": "学校前面有公交站。",
    "cn_pinyin": "Xué xiào qián miàn yǒu gōng jiāo zhàn.",
    "theme": "directions"
  },
  {
    "id": 34,
    "hanzi": "后面",
    "pinyin": "hòu miàn",
    "meaning": "뒤쪽",
    "kr": "건물 뒤에 주차장이 있어요.",
    "cn_sentence": "大楼后面有停车场。",
    "cn_pinyin": "Dà lóu hòu miàn yǒu tíng chē chǎng.",
    "theme": "directions"
  },
  {
    "id": 35,
    "hanzi": "对面",
    "pinyin": "duì miàn",
    "meaning": "맞은편",
    "kr": "은행 맞은편에 우체국이 있어요.",
    "cn_sentence": "银行对面是邮局。",
    "cn_pinyin": "Yín háng duì miàn shì yóu jú.",
    "theme": "directions"
  },
  {
    "id": 36,
    "hanzi": "楼上",
    "pinyin": "lóu shàng",
    "meaning": "위층",
    "kr": "2층에 도서관이 있어요.",
    "cn_sentence": "楼上有图书馆。",
    "cn_pinyin": "Lóu shàng yǒu tú shū guǎn.",
    "theme": "directions"
  },
  {
    "id": 37,
    "hanzi": "楼下",
    "pinyin": "lóu xià",
    "meaning": "아래층",
    "kr": "1층에 식당이 있어요.",
    "cn_sentence": "楼下有餐厅。",
    "cn_pinyin": "Lóu xià yǒu cān tīng.",
    "theme": "directions"
  },
  {
    "id": 38,
    "hanzi": "儿子",
    "pinyin": "ér zi",
    "meaning": "아들",
    "kr": "아들이 축구를 좋아해요.",
    "cn_sentence": "儿子喜欢足球。",
    "cn_pinyin": "Ér zi xǐ huan zú qiú.",
    "theme": "family"
  },
  {
    "id": 39,
    "hanzi": "见面",
    "pinyin": "jiàn miàn",
    "meaning": "만나다",
    "kr": "친구와 주말에 만나기로 했어요.",
    "cn_sentence": "和朋友约好周末见面。",
    "cn_pinyin": "Hé péng you yuē hǎo zhōu mò jiàn miàn.",
    "theme": "other"
  },
  {
    "id": 40,
    "hanzi": "春节",
    "pinyin": "Chūn jié",
    "meaning": "설날·춘절",
    "kr": "설날에 떡국을 먹어요.",
    "cn_sentence": "春节吃年糕汤。",
    "cn_pinyin": "Chūn jié chī nián gāo tāng.",
    "theme": "time"
  },
  {
    "id": 41,
    "hanzi": "漂亮",
    "pinyin": "piào liang",
    "meaning": "예쁘다",
    "kr": "그녀는 정말 예뻐요.",
    "cn_sentence": "她真的很漂亮。",
    "cn_pinyin": "Tā zhēn de hěn piào liang.",
    "theme": "body"
  },
  {
    "id": 42,
    "hanzi": "瓜子脸",
    "pinyin": "guā zi liǎn",
    "meaning": "갸름한 얼굴",
    "kr": "그 여자는 귀여운 깡충얼굴이에요.",
    "cn_sentence": "那个女孩是瓜子脸。",
    "cn_pinyin": "Nà ge nǚ hái shì guā zi liǎn.",
    "theme": "body"
  },
  {
    "id": 43,
    "hanzi": "圆",
    "pinyin": "yuán",
    "meaning": "둥글다",
    "kr": "내 동생은 얼굴이 동그래요.",
    "cn_sentence": "我妹妹的脸圆圆的。",
    "cn_pinyin": "Wǒ mèi mei de liǎn yuán yuán de.",
    "theme": "body"
  },
  {
    "id": 44,
    "hanzi": "瘦",
    "pinyin": "shòu",
    "meaning": "마르다",
    "kr": "그는 운동해서 날씬해요.",
    "cn_sentence": "他因为运动而很瘦。",
    "cn_pinyin": "Tā yīn wèi yùn dòng ér hěn shòu.",
    "theme": "body"
  },
  {
    "id": 45,
    "hanzi": "又…又…",
    "pinyin": "yòu…yòu…",
    "meaning": "~하기도 ~하기도",
    "kr": "그녀는 예쁘고 착해요.",
    "cn_sentence": "她又漂亮又善良。",
    "cn_pinyin": "Tā yòu piào liang yòu shàn liáng.",
    "theme": "grammar"
  },
  {
    "id": 46,
    "hanzi": "帅",
    "pinyin": "shuài",
    "meaning": "잘생기다",
    "kr": "그 남자는 정말 잘생겼어요.",
    "cn_sentence": "那个男人很帅。",
    "cn_pinyin": "Nà ge nán rén hěn shuài.",
    "theme": "body"
  },
  {
    "id": 47,
    "hanzi": "奶奶",
    "pinyin": "nǎi nai",
    "meaning": "할머니",
    "kr": "할머니의 김치는 정말 맛있어요.",
    "cn_sentence": "奶奶的泡菜真的很好吃。",
    "cn_pinyin": "Nǎi nai de pào cài zhēn de hěn hǎo chī.",
    "theme": "family"
  },
  {
    "id": 48,
    "hanzi": "有点儿",
    "pinyin": "yǒu diǎn er",
    "meaning": "조금",
    "kr": "오늘은 좀 피곤해요.",
    "cn_sentence": "今天有点儿累。",
    "cn_pinyin": "Jīn tiān yǒu diǎn er lèi.",
    "theme": "grammar"
  },
  {
    "id": 49,
    "hanzi": "胖",
    "pinyin": "pàng",
    "meaning": "뚱뚱하다",
    "kr": "그는 살이 쪘어요.",
    "cn_sentence": "他胖了。",
    "cn_pinyin": "Tā pàng le.",
    "theme": "body"
  },
  {
    "id": 50,
    "hanzi": "腰",
    "pinyin": "yāo",
    "meaning": "허리",
    "kr": "제 허리가 아파요.",
    "cn_sentence": "我腰疼。",
    "cn_pinyin": "Wǒ yāo téng.",
    "theme": "body"
  },
  {
    "id": 51,
    "hanzi": "背",
    "pinyin": "bèi",
    "meaning": "등",
    "kr": "아기가 제 등에 업혀 있어요.",
    "cn_sentence": "小孩趴在我背上。",
    "cn_pinyin": "Xiǎo hái pā zài wǒ bèi shàng.",
    "theme": "body"
  },
  {
    "id": 52,
    "hanzi": "脖子",
    "pinyin": "bó zi",
    "meaning": "목",
    "kr": "목이 뻣뻣해요.",
    "cn_sentence": "脖子很僵硬。",
    "cn_pinyin": "Bó zi hěn jiāng yìng.",
    "theme": "body"
  },
  {
    "id": 53,
    "hanzi": "肩膀",
    "pinyin": "jiān bǎng",
    "meaning": "어깨",
    "kr": "어깨가 결렸어요.",
    "cn_sentence": "肩膀酸痛。",
    "cn_pinyin": "Jiān bǎng suān tòng.",
    "theme": "body"
  },
  {
    "id": 54,
    "hanzi": "手指头",
    "pinyin": "shǒu zhǐ tou",
    "meaning": "손가락",
    "kr": "손가락을 베였어요.",
    "cn_sentence": "手指头被割伤了。",
    "cn_pinyin": "Shǒu zhǐ tou bèi gē shāng le.",
    "theme": "body"
  },
  {
    "id": 55,
    "hanzi": "脚指头",
    "pinyin": "jiǎo zhǐ tou",
    "meaning": "발가락",
    "kr": "발가락이 저렸어요.",
    "cn_sentence": "脚指头麻了。",
    "cn_pinyin": "Jiǎo zhǐ tou má le.",
    "theme": "body"
  },
  {
    "id": 56,
    "hanzi": "眉毛",
    "pinyin": "méi mao",
    "meaning": "눈썹",
    "kr": "눈썹이 진한 편이에요.",
    "cn_sentence": "眉毛算浓的。",
    "cn_pinyin": "Méi mao suàn nóng de.",
    "theme": "body"
  },
  {
    "id": 57,
    "hanzi": "屁股",
    "pinyin": "pì gu",
    "meaning": "엉덩이",
    "kr": "아이가 엉덩이를 맞았어요.",
    "cn_sentence": "孩子被打屁股了。",
    "cn_pinyin": "Hái zi bèi dǎ pì gu le.",
    "theme": "body"
  },
  {
    "id": 58,
    "hanzi": "洛杉矶",
    "pinyin": "Luò shān jī",
    "meaning": "로스앤젤레스",
    "kr": "내년에 로스앤젤레스에 여행 가고 싶어요.",
    "cn_sentence": "明年我想去洛杉矶旅行。",
    "cn_pinyin": "Míng nián wǒ xiǎng qù Luò shān jī lǚ xíng.",
    "theme": "places"
  },
  {
    "id": 59,
    "hanzi": "个子",
    "pinyin": "gè zi",
    "meaning": "키",
    "kr": "키가 작은 편이에요.",
    "cn_sentence": "个子算小的。",
    "cn_pinyin": "Gè zi suàn xiǎo de.",
    "theme": "body"
  },
  {
    "id": 60,
    "hanzi": "直",
    "pinyin": "zhí",
    "meaning": "곧다·직모",
    "kr": "머리가 곧게 뻗었어요.",
    "cn_sentence": "头发直直的。",
    "cn_pinyin": "Tóu fa zhí zhí de.",
    "theme": "body"
  },
  {
    "id": 61,
    "hanzi": "是…的",
    "pinyin": "shì…de",
    "meaning": "~한 것이다(강조)",
    "kr": "그는 어제 온 거예요.",
    "cn_sentence": "他是昨天来的。",
    "cn_pinyin": "Tā shì zuó tiān lái de.",
    "theme": "grammar"
  },
  {
    "id": 62,
    "hanzi": "不见",
    "pinyin": "bù jiàn",
    "meaning": "안 보이다",
    "kr": "지갑이 안 보여요.",
    "cn_sentence": "钱包不见了。",
    "cn_pinyin": "Qián bāo bù jiàn le.",
    "theme": "grammar"
  },
  {
    "id": 63,
    "hanzi": "报纸",
    "pinyin": "bào zhǐ",
    "meaning": "신문",
    "kr": "아침에 신문을 봐요.",
    "cn_sentence": "早上看报纸。",
    "cn_pinyin": "Zǎo shang kàn bào zhǐ.\n…",
    "theme": "other"
  },
  {
    "id": 64,
    "hanzi": "的时候",
    "pinyin": "…de shí hou",
    "meaning": "~할 때",
    "kr": "비가 올 때 집에 있어요.",
    "cn_sentence": "下雨的时候待在家里。",
    "cn_pinyin": "Xià yǔ de shí hou dāi zài jiā li.",
    "theme": "grammar"
  },
  {
    "id": 65,
    "hanzi": "别",
    "pinyin": "bié",
    "meaning": "~하지 마라",
    "kr": "거기 가지 마세요.",
    "cn_sentence": "别去那里。",
    "cn_pinyin": "Bié qù nà li.",
    "theme": "grammar"
  },
  {
    "id": 66,
    "hanzi": "着急",
    "pinyin": "zháo jí",
    "meaning": "조급하다",
    "kr": "너무 걱정하지 마세요.",
    "cn_sentence": "别着急。",
    "cn_pinyin": "Bié zháo jí.",
    "theme": "other"
  },
  {
    "id": 67,
    "hanzi": "帮",
    "pinyin": "bāng",
    "meaning": "돕다",
    "kr": "좀 도와주실래요?",
    "cn_sentence": "能帮一下我吗？",
    "cn_pinyin": "Néng bāng yí xià wǒ ma?",
    "theme": "other"
  },
  {
    "id": 68,
    "hanzi": "找",
    "pinyin": "zhǎo",
    "meaning": "찾다",
    "kr": "핸드폰을 찾고 있어요.",
    "cn_sentence": "我正在找手机。",
    "cn_pinyin": "Wǒ zhèng zài zhǎo shǒu jī.",
    "theme": "other"
  },
  {
    "id": 69,
    "hanzi": "大伯",
    "pinyin": "dà bó",
    "meaning": "큰아버지",
    "kr": "큰아버지는 의사이십니다.",
    "cn_sentence": "大伯是医生。",
    "cn_pinyin": "Dà bó shì yī shēng.",
    "theme": "family"
  },
  {
    "id": 70,
    "hanzi": "流鼻涕",
    "pinyin": "liú bí tì",
    "meaning": "콧물이 나다",
    "kr": "아이가 콧물을 흘려요.",
    "cn_sentence": "孩子在流鼻涕。",
    "cn_pinyin": "Hái zi zài liú bí tì.",
    "theme": "health"
  },
  {
    "id": 71,
    "hanzi": "肚子",
    "pinyin": "dù zi",
    "meaning": "배",
    "kr": "배가 아파요.",
    "cn_sentence": "肚子疼。",
    "cn_pinyin": "Dù zi téng.",
    "theme": "health"
  },
  {
    "id": 72,
    "hanzi": "拉肚子",
    "pinyin": "lā dù zi",
    "meaning": "설사하다",
    "kr": "설사를 해요.",
    "cn_sentence": "我拉肚子了。",
    "cn_pinyin": "Wǒ lā dù zi le.",
    "theme": "health"
  },
  {
    "id": 73,
    "hanzi": "给",
    "pinyin": "gěi",
    "meaning": "주다",
    "kr": "의사가 약을 주셨어요.",
    "cn_sentence": "医生给我开了药。",
    "cn_pinyin": "Yī shēng gěi wǒ kāi le yào.",
    "theme": "health"
  },
  {
    "id": 74,
    "hanzi": "量体温",
    "pinyin": "liáng tǐ wēn",
    "meaning": "체온을 재다",
    "kr": "체온을 재야 해요.",
    "cn_sentence": "得量一下体温。",
    "cn_pinyin": "Děi liáng yí xià tǐ wēn.",
    "theme": "health"
  },
  {
    "id": 75,
    "hanzi": "开药",
    "pinyin": "kāi yào",
    "meaning": "약을 처방하다",
    "kr": "의사가 감기약을 처방했어요.",
    "cn_sentence": "医生开了感冒药。",
    "cn_pinyin": "Yī shēng kāi le gǎn mào yào.",
    "theme": "health"
  },
  {
    "id": 76,
    "hanzi": "一些",
    "pinyin": "yī xiē",
    "meaning": "조금·약간",
    "kr": "물을 좀 마셔야 해요.",
    "cn_sentence": "需要喝一些水。",
    "cn_pinyin": "Xū yào hē yī xiē shuǐ.",
    "theme": "other"
  },
  {
    "id": 77,
    "hanzi": "发烧",
    "pinyin": "fā shāo",
    "meaning": "열이 나다",
    "kr": "열이 나요.",
    "cn_sentence": "我发烧了。",
    "cn_pinyin": "Wǒ fā shāo le.",
    "theme": "health"
  },
  {
    "id": 78,
    "hanzi": "咳嗽",
    "pinyin": "ké sou",
    "meaning": "기침하다",
    "kr": "기침을 많이 해요.",
    "cn_sentence": "咳得很厉害。",
    "cn_pinyin": "Ké de hěn lì hai.",
    "theme": "health"
  },
  {
    "id": 79,
    "hanzi": "嗓子疼",
    "pinyin": "sǎng zi téng",
    "meaning": "목이 아프다",
    "kr": "목이 아파요.",
    "cn_sentence": "嗓子疼。",
    "cn_pinyin": "Sǎng zi téng.",
    "theme": "health"
  },
  {
    "id": 80,
    "hanzi": "叔叔",
    "pinyin": "shū shu",
    "meaning": "삼촌",
    "kr": "삼촌이 새 차를 샀어요.",
    "cn_sentence": "叔叔买了新车。",
    "cn_pinyin": "Shū shu mǎi le xīn chē.",
    "theme": "family"
  },
  {
    "id": 81,
    "hanzi": "耳朵疼",
    "pinyin": "ěr duo téng",
    "meaning": "귀가 아프다",
    "kr": "귀가 아파요.",
    "cn_sentence": "耳朵疼。",
    "cn_pinyin": "Ěr duo téng.",
    "theme": "health"
  },
  {
    "id": 82,
    "hanzi": "眼睛疼",
    "pinyin": "yǎn jīng téng",
    "meaning": "눈이 아프다",
    "kr": "눈이 아파요.",
    "cn_sentence": "眼睛疼。",
    "cn_pinyin": "Yǎn jīng téng.",
    "theme": "health"
  },
  {
    "id": 83,
    "hanzi": "踢",
    "pinyin": "tī",
    "meaning": "(발로) 차다",
    "kr": "아이들이 축구공을 찼어요.",
    "cn_sentence": "孩子们踢了足球。",
    "cn_pinyin": "Hái zi men tī le zú qiú.",
    "theme": "sports"
  },
  {
    "id": 84,
    "hanzi": "足球",
    "pinyin": "zú qiú",
    "meaning": "축구",
    "kr": "저는 축구를 좋아해요.",
    "cn_sentence": "我喜欢足球。",
    "cn_pinyin": "Wǒ xǐ huan zú qiú.",
    "theme": "sports"
  },
  {
    "id": 85,
    "hanzi": "受",
    "pinyin": "shòu",
    "meaning": "받다·입다",
    "kr": "다리를 다쳤어요.",
    "cn_sentence": "腿受了伤。",
    "cn_pinyin": "Tuǐ shòu le shāng.",
    "theme": "health"
  },
  {
    "id": 86,
    "hanzi": "受伤",
    "pinyin": "shòu shāng",
    "meaning": "다치다",
    "kr": "운동하다가 손가락을 다쳤어요.",
    "cn_sentence": "运动时手指受伤了。",
    "cn_pinyin": "Yùn dòng shí shǒu zhǐ shòu shāng le.",
    "theme": "health"
  },
  {
    "id": 87,
    "hanzi": "需要",
    "pinyin": "xū yào",
    "meaning": "필요하다",
    "kr": "병원에 가야 해요.",
    "cn_sentence": "需要去医院。",
    "cn_pinyin": "Xū yào qù yī yuàn.",
    "theme": "grammar"
  },
  {
    "id": 88,
    "hanzi": "所以",
    "pinyin": "suǒ yǐ",
    "meaning": "그래서",
    "kr": "아파서 병원에 갔어요.",
    "cn_sentence": "因为生病，所以去了医院。",
    "cn_pinyin": "Yīn wéi shēng bìng, suǒ yǐ qù le yī yuàn.",
    "theme": "grammar"
  },
  {
    "id": 89,
    "hanzi": "能",
    "pinyin": "néng",
    "meaning": "~할 수 있다",
    "kr": "저는 빨리 걸을 수 있어요.",
    "cn_sentence": "我能走得快。",
    "cn_pinyin": "Wǒ néng zǒu de kuài.",
    "theme": "grammar"
  },
  {
    "id": 90,
    "hanzi": "不能",
    "pinyin": "bù néng",
    "meaning": "~할 수 없다",
    "kr": "오늘 학교에 못 가요.",
    "cn_sentence": "今天不能去学校。",
    "cn_pinyin": "Jīn tiān bù néng qù xué xiào.",
    "theme": "grammar"
  },
  {
    "id": 91,
    "hanzi": "姑姑",
    "pinyin": "gū gu",
    "meaning": "고모",
    "kr": "고모가 우리 집에 왔어요.",
    "cn_sentence": "姑姑来我们家了。",
    "cn_pinyin": "Gū gu lái wǒ men jiā le.",
    "theme": "family"
  },
  {
    "id": 92,
    "hanzi": "病假",
    "pinyin": "bìng jià",
    "meaning": "병가",
    "kr": "병가를 냈어요.",
    "cn_sentence": "我请了病假。",
    "cn_pinyin": "Wǒ qǐng le bìng jià.",
    "theme": "health"
  },
  {
    "id": 93,
    "hanzi": "请假",
    "pinyin": "qǐng jià",
    "meaning": "휴가를 내다",
    "kr": "선생님께 휴가를 여쭤봐야 해요.",
    "cn_sentence": "得跟老师请假。",
    "cn_pinyin": "Děi gēn lǎo shī qǐng jià.",
    "theme": "health"
  },
  {
    "id": 94,
    "hanzi": "请病假",
    "pinyin": "qǐng bìng jià",
    "meaning": "병가를 내다",
    "kr": "아파서 병가를 신청했어요.",
    "cn_sentence": "因为生病请了病假。",
    "cn_pinyin": "Yīn wèi shēng bìng qǐng le bìng jià.",
    "theme": "health"
  },
  {
    "id": 95,
    "hanzi": "暖和",
    "pinyin": "nuǎn huo",
    "meaning": "따뜻하다",
    "kr": "날씨가 따뜻해졌어요.",
    "cn_sentence": "天气变暖和了。",
    "cn_pinyin": "Tiān qì biàn nuǎn huo le.",
    "theme": "weather"
  },
  {
    "id": 96,
    "hanzi": "雾",
    "pinyin": "wù",
    "meaning": "안개",
    "kr": "오늘 아침에 안개가 많이 꼈어요.",
    "cn_sentence": "今天早上雾很大。",
    "cn_pinyin": "Jīn tiān zǎo shang wù hěn dà.",
    "theme": "weather"
  },
  {
    "id": 97,
    "hanzi": "雷",
    "pinyin": "léi",
    "meaning": "천둥",
    "kr": "천둥이 치는 소리가 들려요.",
    "cn_sentence": "能听见打雷的声音。",
    "cn_pinyin": "Néng tīng jiàn dǎ léi de shēng yīn.",
    "theme": "weather"
  },
  {
    "id": 98,
    "hanzi": "雷雨",
    "pinyin": "léi yǔ",
    "meaning": "뇌우",
    "kr": "뇌우가 곧 올 거예요.",
    "cn_sentence": "雷雨马上要来了。",
    "cn_pinyin": "Léi yǔ mǎ shàng yào lái le.",
    "theme": "weather"
  },
  {
    "id": 99,
    "hanzi": "凉快",
    "pinyin": "liáng kuai",
    "meaning": "시원하다",
    "kr": "바람이 불어서 시원해요.",
    "cn_sentence": "刮风了，很凉快。",
    "cn_pinyin": "Guā fēng le, hěn liáng kuai.",
    "theme": "weather"
  },
  {
    "id": 100,
    "hanzi": "干燥",
    "pinyin": "gān zào",
    "meaning": "건조하다",
    "kr": "겨울에는 공기가 건조해요.",
    "cn_sentence": "冬天空气很干燥。",
    "cn_pinyin": "Dōng tiān kōng qì hěn gān zào.",
    "theme": "weather"
  },
  {
    "id": 101,
    "hanzi": "纽约",
    "pinyin": "Niǔ yuē",
    "meaning": "뉴욕",
    "kr": "뉴욕에서 크리스마스를 보냈어요.",
    "cn_sentence": "在纽约度过了圣诞节。",
    "cn_pinyin": "Zài Niǔ yuē dù guò le Shèng dàn jié.",
    "theme": "places"
  },
  {
    "id": 102,
    "hanzi": "潮湿",
    "pinyin": "cháo shī",
    "meaning": "습하다",
    "kr": "장마철에는 집 안이 습해요.",
    "cn_sentence": "梅雨季节家里很潮湿。",
    "cn_pinyin": "Méi yǔ jì jié jiā lǐ hěn cháo shī.",
    "theme": "weather"
  },
  {
    "id": 103,
    "hanzi": "冰雹",
    "pinyin": "bīng báo",
    "meaning": "우박",
    "kr": "우박이 내렸어요.",
    "cn_sentence": "下冰雹了。",
    "cn_pinyin": "Xià bīng báo le.",
    "theme": "weather"
  },
  {
    "id": 104,
    "hanzi": "发大水",
    "pinyin": "fā dà shuǐ",
    "meaning": "홍수가 나다",
    "kr": "비가 많이 와서 홍수가 났어요.",
    "cn_sentence": "雨下得很大，发大水了。",
    "cn_pinyin": "Yǔ xià de hěn dà, fā dà shuǐ le.",
    "theme": "weather"
  },
  {
    "id": 105,
    "hanzi": "龙卷风",
    "pinyin": "lóng juǎn fēng",
    "meaning": "토네이도",
    "kr": "토네이도가 다가오고 있어요.",
    "cn_sentence": "龙卷风正在靠近。",
    "cn_pinyin": "Lóng juǎn fēng zhèng zài kào jìn.",
    "theme": "weather"
  },
  {
    "id": 106,
    "hanzi": "沙尘暴",
    "pinyin": "shā chén bào",
    "meaning": "황사",
    "kr": "황사가 심해서 외출하기 어려워요.",
    "cn_sentence": "沙尘暴很严重，很难出门。",
    "cn_pinyin": "Shā chén bào hěn yán zhòng, hěn nán chū mén.",
    "theme": "weather"
  },
  {
    "id": 107,
    "hanzi": "亲爱",
    "pinyin": "qīn ài",
    "meaning": "친애하는",
    "kr": "친애하는 친구에게 편지를 썼어요.",
    "cn_sentence": "给亲爱的朋友写了信。",
    "cn_pinyin": "Gěi qīn ài de péng you xiě le xìn.",
    "theme": "grammar"
  },
  {
    "id": 108,
    "hanzi": "如果",
    "pinyin": "rú guǒ",
    "meaning": "만약",
    "kr": "비가 오면 집에 있을 거예요.",
    "cn_sentence": "如果下雨，我就待在家里。",
    "cn_pinyin": "Rú guǒ xià yǔ, wǒ jiù dāi zài jiā li.",
    "theme": "grammar"
  },
  {
    "id": 109,
    "hanzi": "暑假",
    "pinyin": "shǔ jià",
    "meaning": "여름방학",
    "kr": "여름방학에 바다에 갈 거예요.",
    "cn_sentence": "暑假我要去海边。",
    "cn_pinyin": "Shǔ jià wǒ yào qù hǎi biān.",
    "theme": "time"
  },
  {
    "id": 110,
    "hanzi": "鞋",
    "pinyin": "xié",
    "meaning": "신발",
    "kr": "새 신을 샀어요.",
    "cn_sentence": "我买了新鞋。",
    "cn_pinyin": "Wǒ mǎi le xīn xié.",
    "theme": "clothing"
  },
  {
    "id": 111,
    "hanzi": "凉鞋",
    "pinyin": "liáng xié",
    "meaning": "샌들",
    "kr": "여름에는 샌들을 신어요.",
    "cn_sentence": "夏天穿凉鞋。",
    "cn_pinyin": "Xià tiān chuān liáng xié.",
    "theme": "clothing"
  },
  {
    "id": 112,
    "hanzi": "因为",
    "pinyin": "yīn wèi",
    "meaning": "~때문에",
    "kr": "비가 와서 집에 있었어요.",
    "cn_sentence": "因为下雨，所以待在家里了。",
    "cn_pinyin": "Yīn wèi xià yǔ, suǒ yǐ dāi zài jiā li le.",
    "theme": "grammar"
  },
  {
    "id": 113,
    "hanzi": "寒假",
    "pinyin": "hán jià",
    "meaning": "겨울방학",
    "kr": "겨울방학에 스키를 탈 거예요.",
    "cn_sentence": "寒假我要去滑雪。",
    "cn_pinyin": "Hán jià wǒ yào qù huá xuě.",
    "theme": "time"
  },
  {
    "id": 114,
    "hanzi": "不用",
    "pinyin": "bù yòng",
    "meaning": "~할 필요 없다",
    "kr": "오늘은 우산을 안 가져가도 돼요.",
    "cn_sentence": "今天不用带雨伞。",
    "cn_pinyin": "Jīn tiān bù yòng dài yǔ sǎn.",
    "theme": "grammar"
  },
  {
    "id": 115,
    "hanzi": "围巾",
    "pinyin": "wéi jīn",
    "meaning": "목도리·스카프",
    "kr": "목도리를 두르면 따뜻해요.",
    "cn_sentence": "戴上围巾就暖和了。",
    "cn_pinyin": "Dài shàng wéi jīn jiù nuǎn huo le.",
    "theme": "clothing"
  },
  {
    "id": 116,
    "hanzi": "帽子",
    "pinyin": "mào zi",
    "meaning": "모자",
    "kr": "겨울에는 모자를 써야 해요.",
    "cn_sentence": "冬天要戴帽子。",
    "cn_pinyin": "Dōng tiān yào dài mào zi.",
    "theme": "clothing"
  },
  {
    "id": 117,
    "hanzi": "手套",
    "pinyin": "shǒu tào",
    "meaning": "장갑",
    "kr": "장갑을 끼고 나가세요.",
    "cn_sentence": "戴上手套再出门。",
    "cn_pinyin": "Dài shàng shǒu tào zài chū mén.",
    "theme": "clothing"
  },
  {
    "id": 118,
    "hanzi": "最好",
    "pinyin": "zuì hǎo",
    "meaning": "~하는 게 좋다",
    "kr": "지금 집에 가는 게 좋을 것 같아요.",
    "cn_sentence": "最好现在回家。",
    "cn_pinyin": "Zuì hǎo xiàn zài huí jiā.",
    "theme": "grammar"
  },
  {
    "id": 119,
    "hanzi": "雨伞",
    "pinyin": "yǔ sǎn",
    "meaning": "우산",
    "kr": "비가 올 것 같아서 우산을 챙겼어요.",
    "cn_sentence": "好像要下雨，所以带了雨伞。",
    "cn_pinyin": "Hǎo xiàng yào xià yǔ, suǒ yǐ dài le yǔ sǎn.",
    "theme": "clothing"
  },
  {
    "id": 120,
    "hanzi": "祝",
    "pinyin": "zhù",
    "meaning": "(축하를) 빌다",
    "kr": "생일 축하해요!",
    "cn_sentence": "祝你生日快乐！",
    "cn_pinyin": "Zhù nǐ shēng rì kuài lè!",
    "theme": "grammar"
  },
  {
    "id": 121,
    "hanzi": "西装",
    "pinyin": "xī zhuāng",
    "meaning": "양복",
    "kr": "정장을 입고 회의에 갔어요.",
    "cn_sentence": "穿着西装去开会了。",
    "cn_pinyin": "Chuān zhe xī zhuāng qù kāi huì le.",
    "theme": "clothing"
  },
  {
    "id": 122,
    "hanzi": "双",
    "pinyin": "shuāng",
    "meaning": "켤레(양사)",
    "kr": "신발 한 켤레를 샀어요.",
    "cn_sentence": "买了一双鞋。",
    "cn_pinyin": "Mǎi le yī shuāng xié.",
    "theme": "clothing"
  },
  {
    "id": 123,
    "hanzi": "皮靴",
    "pinyin": "pí xuē",
    "meaning": "가죽 부츠",
    "kr": "겨울에는 가죽장화를 신어요.",
    "cn_sentence": "冬天穿皮靴。",
    "cn_pinyin": "Dōng tiān chuān pí xuē.",
    "theme": "clothing"
  },
  {
    "id": 124,
    "hanzi": "试",
    "pinyin": "shì",
    "meaning": "입어보다·해보다",
    "kr": "옷을 입어 봐도 될까요?",
    "cn_sentence": "可以试一下衣服吗？",
    "cn_pinyin": "Kě yǐ shì yī xià yī fu ma?",
    "theme": "clothing"
  },
  {
    "id": 125,
    "hanzi": "当然",
    "pinyin": "dāng rán",
    "meaning": "당연히·물론",
    "kr": "물론 도와드릴 수 있어요.",
    "cn_sentence": "当然可以帮您。",
    "cn_pinyin": "Dāng rán kě yǐ bāng nín.",
    "theme": "grammar"
  },
  {
    "id": 126,
    "hanzi": "合适",
    "pinyin": "hé shì",
    "meaning": "알맞다",
    "kr": "이 신발이 제 발에 잘 맞아요.",
    "cn_sentence": "这双鞋我穿很合适。",
    "cn_pinyin": "Zhè shuāng xié wǒ chuān hěn hé shì.",
    "theme": "clothing"
  },
  {
    "id": 127,
    "hanzi": "千",
    "pinyin": "qiān",
    "meaning": "천(1,000)",
    "kr": "이 가방은 천 위안이에요.",
    "cn_sentence": "这个包一千元。",
    "cn_pinyin": "Zhè ge bāo yī qiān yuán.",
    "theme": "grammar"
  },
  {
    "id": 128,
    "hanzi": "太…了",
    "pinyin": "tài…le",
    "meaning": "너무 ~하다",
    "kr": "날씨가 너무 더워요.",
    "cn_sentence": "天气太热了。",
    "cn_pinyin": "Tiān qì tài rè le.",
    "theme": "grammar"
  },
  {
    "id": 129,
    "hanzi": "小时候",
    "pinyin": "xiǎo shí hou",
    "meaning": "어렸을 때",
    "kr": "어렸을 때 시골에 살았어요.",
    "cn_sentence": "小时候住在乡下。",
    "cn_pinyin": "Xiǎo shí hou zhù zài xiāng xià.",
    "theme": "time"
  },
  {
    "id": 130,
    "hanzi": "加拿大",
    "pinyin": "Jiā ná dà",
    "meaning": "캐나다",
    "kr": "저는 캐나다에 가고 싶어요.",
    "cn_sentence": "我想去加拿大。",
    "cn_pinyin": "Wǒ xiǎng qù Jiā ná dà.",
    "theme": "places"
  },
  {
    "id": 131,
    "hanzi": "滑冰",
    "pinyin": "huá bīng",
    "meaning": "스케이트 타다",
    "kr": "겨울에 스케이트를 타요.",
    "cn_sentence": "冬天滑冰。",
    "cn_pinyin": "Dōng tiān huá bīng.",
    "theme": "sports"
  },
  {
    "id": 132,
    "hanzi": "滑雪",
    "pinyin": "huá xuě",
    "meaning": "스키 타다",
    "kr": "스키를 배우고 싶어요.",
    "cn_sentence": "我想学滑雪。",
    "cn_pinyin": "Wǒ xiǎng xué huá xuě.",
    "theme": "sports"
  },
  {
    "id": 133,
    "hanzi": "太阳",
    "pinyin": "tài yáng",
    "meaning": "태양",
    "kr": "태양이 뜨거워요.",
    "cn_sentence": "太阳很晒。",
    "cn_pinyin": "Tài yáng hěn shài.",
    "theme": "weather"
  },
  {
    "id": 134,
    "hanzi": "羽毛",
    "pinyin": "yǔ máo",
    "meaning": "깃털",
    "kr": "새 깃털이 가벼워요.",
    "cn_sentence": "羽毛很轻。",
    "cn_pinyin": "Yǔ máo hěn qīng.",
    "theme": "sports"
  },
  {
    "id": 135,
    "hanzi": "羽毛球",
    "pinyin": "yǔ máo qiú",
    "meaning": "배드민턴",
    "kr": "배드민턴을 칠 수 있어요?",
    "cn_sentence": "你会打羽毛球吗？",
    "cn_pinyin": "Nǐ huì dǎ yǔ máo qiú ma?",
    "theme": "sports"
  },
  {
    "id": 136,
    "hanzi": "排球",
    "pinyin": "pái qiú",
    "meaning": "배구",
    "kr": "배구는 재미있는 운동이에요.",
    "cn_sentence": "排球是有趣的运动。",
    "cn_pinyin": "Pái qiú shì yǒu qù de yùn dòng.",
    "theme": "sports"
  },
  {
    "id": 137,
    "hanzi": "乒乓球",
    "pinyin": "pīng pāng qiú",
    "meaning": "탁구",
    "kr": "탁구를 같이 칠래요?",
    "cn_sentence": "一起打乒乓球吗？",
    "cn_pinyin": "Yī qǐ dǎ pīng pāng qiú ma?",
    "theme": "sports"
  },
  {
    "id": 138,
    "hanzi": "钓鱼",
    "pinyin": "diào yú",
    "meaning": "낚시하다",
    "kr": "주말에 낚시를 갈 거예요.",
    "cn_sentence": "周末要去钓鱼。",
    "cn_pinyin": "Zhōu mò yào qù diào yú.",
    "theme": "sports"
  },
  {
    "id": 139,
    "hanzi": "件",
    "pinyin": "jiàn",
    "meaning": "벌·개(양사)",
    "kr": "옷 한 벌을 샀어요.",
    "cn_sentence": "买了一件衣服。",
    "cn_pinyin": "Mǎi le yī jiàn yī fu.",
    "theme": "clothing"
  },
  {
    "id": 140,
    "hanzi": "游泳衣",
    "pinyin": "yóu yǒng yī",
    "meaning": "수영복",
    "kr": "수영복을 챙겼어요.",
    "cn_sentence": "带了游泳衣。",
    "cn_pinyin": "Dài le yóu yǒng yī.",
    "theme": "clothing"
  },
  {
    "id": 141,
    "hanzi": "几",
    "pinyin": "jǐ",
    "meaning": "몇",
    "kr": "사과가 몇 개 있어요?",
    "cn_sentence": "有几个苹果？",
    "cn_pinyin": "Yǒu jǐ ge píng guǒ?",
    "theme": "grammar"
  },
  {
    "id": 142,
    "hanzi": "顶",
    "pinyin": "dǐng",
    "meaning": "개(모자 양사)",
    "kr": "모자 한 개를 샀어요.",
    "cn_sentence": "买了一顶帽子。",
    "cn_pinyin": "Mǎi le yī dǐng mào zi.",
    "theme": "clothing"
  },
  {
    "id": 143,
    "hanzi": "副",
    "pinyin": "fù",
    "meaning": "벌(장갑 양사)",
    "kr": "장갑 한 켤레가 필요해요.",
    "cn_sentence": "需要一副手套。",
    "cn_pinyin": "Xū yào yī fù shǒu tào.",
    "theme": "clothing"
  },
  {
    "id": 144,
    "hanzi": "耳环",
    "pinyin": "ěr huán",
    "meaning": "귀걸이",
    "kr": "귀걸이가 예뻐요.",
    "cn_sentence": "耳环很漂亮。",
    "cn_pinyin": "Ěr huán hěn piào liang.",
    "theme": "clothing"
  },
  {
    "id": 145,
    "hanzi": "已经",
    "pinyin": "yǐ jīng",
    "meaning": "이미·벌써",
    "kr": "벌써 10시예요.",
    "cn_sentence": "已经十点了。",
    "cn_pinyin": "Yǐ jīng shí diǎn le.",
    "theme": "time"
  },
  {
    "id": 146,
    "hanzi": "项链",
    "pinyin": "xiàng liàn",
    "meaning": "목걸이",
    "kr": "금 목걸이를 선물 받았어요.",
    "cn_sentence": "收到了金项链礼物。",
    "cn_pinyin": "Shōu dào le jīn xiàng liàn lǐ wù.",
    "theme": "clothing"
  },
  {
    "id": 147,
    "hanzi": "万",
    "pinyin": "wàn",
    "meaning": "만(10,000)",
    "kr": "이 차는 만 불이에요.",
    "cn_sentence": "这辆车一万美元。",
    "cn_pinyin": "Zhè liàng chē yī wàn měi yuán.",
    "theme": "grammar"
  },
  {
    "id": 148,
    "hanzi": "物理",
    "pinyin": "wù lǐ",
    "meaning": "물리",
    "kr": "물리는 재미있어요.",
    "cn_sentence": "物理很有趣。",
    "cn_pinyin": "Wù lǐ hěn yǒu qù.",
    "theme": "subjects"
  },
  {
    "id": 149,
    "hanzi": "生物",
    "pinyin": "shēng wù",
    "meaning": "생물",
    "kr": "생물 수업이 어려워요.",
    "cn_sentence": "生物课很难。",
    "cn_pinyin": "Shēng wù kè hěn nán.",
    "theme": "subjects"
  },
  {
    "id": 150,
    "hanzi": "化学",
    "pinyin": "huà xué",
    "meaning": "화학",
    "kr": "화학 실험이 위험해요.",
    "cn_sentence": "化学实验很危险。",
    "cn_pinyin": "Huà xué shí yàn hěn wēi xiǎn.",
    "theme": "subjects"
  },
  {
    "id": 151,
    "hanzi": "地理",
    "pinyin": "dì lǐ",
    "meaning": "지리",
    "kr": "지리 시간에 세계 지도를 봤어요.",
    "cn_sentence": "地理课上看了世界地图。",
    "cn_pinyin": "Dì lǐ kè shàng kàn le shì jiè dì tú.",
    "theme": "subjects"
  },
  {
    "id": 152,
    "hanzi": "对…好",
    "pinyin": "duì…hǎo",
    "meaning": "~에게 잘하다·좋다",
    "kr": "운동은 건강에 좋아요.",
    "cn_sentence": "运动对健康好。",
    "cn_pinyin": "Yùn dòng duì jiàn kāng hǎo.",
    "theme": "grammar"
  },
  {
    "id": 153,
    "hanzi": "对…感兴趣",
    "pinyin": "duì…gǎn xìng qù",
    "meaning": "~에 관심이 있다",
    "kr": "저는 한국어에 관심이 있어요.",
    "cn_sentence": "我对韩语感兴趣。",
    "cn_pinyin": "Wǒ duì Hán yǔ gǎn xìng qù.",
    "theme": "grammar"
  },
  {
    "id": 154,
    "hanzi": "觉得",
    "pinyin": "jué de",
    "meaning": "~라고 생각하다",
    "kr": "오늘 날씨가 좋다고 생각해요.",
    "cn_sentence": "我觉得今天天气好。",
    "cn_pinyin": "Wǒ jué de jīn tiān tiān qì hǎo.",
    "theme": "subjects"
  },
  {
    "id": 155,
    "hanzi": "有用",
    "pinyin": "yǒu yòng",
    "meaning": "유용하다",
    "kr": "한국어는 유용해요.",
    "cn_sentence": "韩语很有用。",
    "cn_pinyin": "Hán yǔ hěn yǒu yòng.",
    "theme": "subjects"
  },
  {
    "id": 156,
    "hanzi": "难",
    "pinyin": "nán",
    "meaning": "어렵다",
    "kr": "수학 문제가 어려워요.",
    "cn_sentence": "数学题很难。",
    "cn_pinyin": "Shù xué tí hěn nán.",
    "theme": "subjects"
  },
  {
    "id": 157,
    "hanzi": "容易",
    "pinyin": "róng yì",
    "meaning": "쉽다",
    "kr": "이 문제는 쉬워요.",
    "cn_sentence": "这个问题很容易。",
    "cn_pinyin": "Zhè ge wèn tí hěn róng yì.",
    "theme": "subjects"
  },
  {
    "id": 158,
    "hanzi": "写",
    "pinyin": "xiě",
    "meaning": "쓰다",
    "kr": "이름을 적으세요.",
    "cn_sentence": "请写名字。",
    "cn_pinyin": "Qǐng xiě míng zi.",
    "theme": "subjects"
  },
  {
    "id": 159,
    "hanzi": "科目",
    "pinyin": "kē mù",
    "meaning": "과목",
    "kr": "어떤 과목을 좋아해요?",
    "cn_sentence": "你喜欢什么科目？",
    "cn_pinyin": "Nǐ xǐ huan shén me kē mù?",
    "theme": "subjects"
  },
  {
    "id": 160,
    "hanzi": "为什么",
    "pinyin": "wèi shén me",
    "meaning": "왜",
    "kr": "왜 한국어를 배워요?",
    "cn_sentence": "为什么学韩语？",
    "cn_pinyin": "Wèi shén me xué Hán yǔ?",
    "theme": "subjects"
  },
  {
    "id": 161,
    "hanzi": "意思",
    "pinyin": "yì si",
    "meaning": "뜻·의미",
    "kr": "이 단어의 뜻이 뭐예요?",
    "cn_sentence": "这个单词的意思是什么？",
    "cn_pinyin": "Zhè ge dān cí de yì si shì shén me?",
    "theme": "subjects"
  },
  {
    "id": 162,
    "hanzi": "有意思",
    "pinyin": "yǒu yì si",
    "meaning": "재미있다",
    "kr": "이 영화는 재미있어요.",
    "cn_sentence": "这部电影很有意思。",
    "cn_pinyin": "Zhè bù diàn yǐng hěn yǒu yì si.",
    "theme": "subjects"
  },
  {
    "id": 163,
    "hanzi": "教",
    "pinyin": "jiāo",
    "meaning": "가르치다",
    "kr": "선생님이 수학을 가르쳐요.",
    "cn_sentence": "老师教数学。",
    "cn_pinyin": "Lǎo shī jiāo shù xué.",
    "theme": "subjects"
  },
  {
    "id": 164,
    "hanzi": "功课",
    "pinyin": "gōng kè",
    "meaning": "숙제",
    "kr": "숙제를 다 했어요.",
    "cn_sentence": "功课做完了。",
    "cn_pinyin": "Gōng kè zuò wán le.",
    "theme": "subjects"
  },
  {
    "id": 165,
    "hanzi": "测验",
    "pinyin": "cè yàn",
    "meaning": "시험·테스트",
    "kr": "다음 주에 시험이 있어요.",
    "cn_sentence": "下周有测验。",
    "cn_pinyin": "Xià zhōu yǒu cè yàn.",
    "theme": "subjects"
  },
  {
    "id": 166,
    "hanzi": "考试",
    "pinyin": "kǎo shì",
    "meaning": "시험",
    "kr": "기말고사를 잘 봤어요.",
    "cn_sentence": "期末考试考得好。",
    "cn_pinyin": "Qī mò kǎo shì kǎo de hǎo.",
    "theme": "subjects"
  },
  {
    "id": 167,
    "hanzi": "学期",
    "pinyin": "xué qī",
    "meaning": "학기",
    "kr": "이번 학기에는 열심히 공부할 거예요.",
    "cn_sentence": "这学期我会努力学习。",
    "cn_pinyin": "Zhè xué qī wǒ huì nǔ lì xué xí.",
    "theme": "subjects"
  },
  {
    "id": 168,
    "hanzi": "介绍",
    "pinyin": "jiè shào",
    "meaning": "소개하다",
    "kr": "제 친구를 소개할게요.",
    "cn_sentence": "我来介绍我的朋友。",
    "cn_pinyin": "Wǒ lái jiè shào wǒ de péng you.",
    "theme": "subjects"
  },
  {
    "id": 169,
    "hanzi": "幢",
    "pinyin": "zhuàng",
    "meaning": "채(건물 양사)",
    "kr": "건물 한 채를 세웠어요.",
    "cn_sentence": "建了一幢楼。",
    "cn_pinyin": "Jiàn le yī zhuàng lóu.",
    "theme": "facilities"
  },
  {
    "id": 170,
    "hanzi": "教学",
    "pinyin": "jiào xué",
    "meaning": "교학·수업",
    "kr": "이 학교는 교학 품질이 높아요.",
    "cn_sentence": "这所学校教学质量高。",
    "cn_pinyin": "Zhè suǒ xué xiào jiào xué zhì liàng gāo.",
    "theme": "subjects"
  },
  {
    "id": 171,
    "hanzi": "图书馆",
    "pinyin": "tú shū guǎn",
    "meaning": "도서관",
    "kr": "도서관에서 책을 빌렸어요.",
    "cn_sentence": "在图书馆借了书。",
    "cn_pinyin": "Zài tú shū guǎn jiè le shū.",
    "theme": "facilities"
  },
  {
    "id": 172,
    "hanzi": "礼堂",
    "pinyin": "lǐ táng",
    "meaning": "강당",
    "kr": "강당에서 공연이 있어요.",
    "cn_sentence": "礼堂里有演出。",
    "cn_pinyin": "Lǐ táng lǐ yǒu yǎn chū.",
    "theme": "facilities"
  },
  {
    "id": 173,
    "hanzi": "操场",
    "pinyin": "cāo chǎng",
    "meaning": "운동장",
    "kr": "운동장에서 달리기를 해요.",
    "cn_sentence": "在操场上跑步。",
    "cn_pinyin": "Zài cāo chǎng shàng pǎo bù.",
    "theme": "facilities"
  },
  {
    "id": 174,
    "hanzi": "体育馆",
    "pinyin": "tǐ yù guǎn",
    "meaning": "체육관",
    "kr": "체육관에서 농구를 해요.",
    "cn_sentence": "在体育馆打篮球。",
    "cn_pinyin": "Zài tǐ yù guǎn dǎ lán qiú.",
    "theme": "facilities"
  },
  {
    "id": 175,
    "hanzi": "篮球场",
    "pinyin": "lán qiú chǎng",
    "meaning": "농구장",
    "kr": "농구장에서 경기를 했어요.",
    "cn_sentence": "在篮球场上比赛了。",
    "cn_pinyin": "Zài lán qiú chǎng shàng bǐ sài le.",
    "theme": "facilities"
  },
  {
    "id": 176,
    "hanzi": "足球场",
    "pinyin": "zú qiú chǎng",
    "meaning": "축구장",
    "kr": "축구장에 사람이 많아요.",
    "cn_sentence": "足球场上人很多。",
    "cn_pinyin": "Zú qiú chǎng shàng rén hěn duō.",
    "theme": "facilities"
  },
  {
    "id": 177,
    "hanzi": "游泳池",
    "pinyin": "yóu yǒng chí",
    "meaning": "수영장",
    "kr": "수영장에 같이 갈래요?",
    "cn_sentence": "一起去游泳池吗？",
    "cn_pinyin": "Yī qǐ qù yóu yǒng chí ma?",
    "theme": "facilities"
  },
  {
    "id": 178,
    "hanzi": "停车场",
    "pinyin": "tíng chē chǎng",
    "meaning": "주차장",
    "kr": "주차장에 차가 많아요.",
    "cn_sentence": "停车场里车很多。",
    "cn_pinyin": "Tíng chē chǎng lǐ chē hěn duō.",
    "theme": "facilities"
  },
  {
    "id": 179,
    "hanzi": "铅笔",
    "pinyin": "qiān bǐ",
    "meaning": "연필",
    "kr": "연필로 쓰세요.",
    "cn_sentence": "请用铅笔写。",
    "cn_pinyin": "Qǐng yòng qiān bǐ xiě.",
    "theme": "stationery"
  },
  {
    "id": 180,
    "hanzi": "钢笔",
    "pinyin": "gāng bǐ",
    "meaning": "만년필",
    "kr": "만년필이 없어졌어요.",
    "cn_sentence": "钢笔不见了。",
    "cn_pinyin": "Gāng bǐ bù jiàn le.",
    "theme": "stationery"
  },
  {
    "id": 181,
    "hanzi": "尺子",
    "pinyin": "chǐ zi",
    "meaning": "자",
    "kr": "자로 길이를 재세요.",
    "cn_sentence": "用尺子量长度。",
    "cn_pinyin": "Yòng chǐ zi liáng cháng dù.",
    "theme": "stationery"
  },
  {
    "id": 182,
    "hanzi": "橡皮",
    "pinyin": "xiàng pí",
    "meaning": "지우개",
    "kr": "지우개로 지우세요.",
    "cn_sentence": "用橡皮擦掉。",
    "cn_pinyin": "Yòng xiàng pí cā diào.",
    "theme": "stationery"
  },
  {
    "id": 183,
    "hanzi": "白板",
    "pinyin": "bái bǎn",
    "meaning": "화이트보드",
    "kr": "칠판에 글을 썼어요.",
    "cn_sentence": "在白板上写了字。",
    "cn_pinyin": "Zài bái bǎn shàng xiě le zì.",
    "theme": "stationery"
  },
  {
    "id": 184,
    "hanzi": "卷笔刀",
    "pinyin": "juǎn bǐ dāo",
    "meaning": "연필깎이",
    "kr": "연필 깎기가 필요해요.",
    "cn_sentence": "需要卷笔刀。",
    "cn_pinyin": "Xū yào juǎn bǐ dāo.",
    "theme": "stationery"
  },
  {
    "id": 185,
    "hanzi": "练习本",
    "pinyin": "liàn xí běn",
    "meaning": "공책·연습장",
    "kr": "공책을 샀어요.",
    "cn_sentence": "买了练习本。",
    "cn_pinyin": "Mǎi le liàn xí běn.",
    "theme": "stationery"
  },
  {
    "id": 186,
    "hanzi": "计算器",
    "pinyin": "jì suàn qì",
    "meaning": "계산기",
    "kr": "계산기로 계산했어요.",
    "cn_sentence": "用计算器算了。",
    "cn_pinyin": "Yòng jì suàn qì suàn le.",
    "theme": "stationery"
  },
  {
    "id": 187,
    "hanzi": "教室",
    "pinyin": "jiào shì",
    "meaning": "교실",
    "kr": "교실에 학생이 많아요.",
    "cn_sentence": "教室里学生很多。",
    "cn_pinyin": "Jiào shì lǐ xué shēng hěn duō.",
    "theme": "facilities"
  },
  {
    "id": 188,
    "hanzi": "三层",
    "pinyin": "sān céng",
    "meaning": "3층",
    "kr": "도서관은 3층에 있어요.",
    "cn_sentence": "图书馆在三层。",
    "cn_pinyin": "Tú shū guǎn zài sān céng.",
    "theme": "facilities"
  },
  {
    "id": 189,
    "hanzi": "旁边",
    "pinyin": "páng biān",
    "meaning": "옆·옆쪽",
    "kr": "우체국 옆에 은행이 있어요.",
    "cn_sentence": "邮局旁边有银行。",
    "cn_pinyin": "Yóu jú páng biān yǒu yín háng.",
    "theme": "directions"
  },
  {
    "id": 190,
    "hanzi": "实验",
    "pinyin": "shí yàn",
    "meaning": "실험",
    "kr": "화학 실험을 했어요.",
    "cn_sentence": "做了化学实验。",
    "cn_pinyin": "Zuò le huà xué shí yàn.",
    "theme": "facilities"
  },
  {
    "id": 191,
    "hanzi": "实验室",
    "pinyin": "shí yàn shì",
    "meaning": "실험실",
    "kr": "실험실에 들어가지 마세요.",
    "cn_sentence": "请不要进实验室。",
    "cn_pinyin": "Qǐng bú yào jìn shí yàn shì.",
    "theme": "facilities"
  },
  {
    "id": 192,
    "hanzi": "隔壁",
    "pinyin": "gé bì",
    "meaning": "옆집·이웃",
    "kr": "우리 옆집에 새 가족이 이사 왔어요.",
    "cn_sentence": "隔壁搬来了新邻居。",
    "cn_pinyin": "Gé bì bān lái le xīn lín jū.",
    "theme": "facilities"
  },
  {
    "id": 193,
    "hanzi": "男",
    "pinyin": "nán",
    "meaning": "남자",
    "kr": "남자 화장실은 오른쪽에 있어요.",
    "cn_sentence": "男厕所在右边。",
    "cn_pinyin": "Nán cè suǒ zài yòu biān.",
    "theme": "facilities"
  },
  {
    "id": 194,
    "hanzi": "厕所",
    "pinyin": "cè suǒ",
    "meaning": "화장실",
    "kr": "화장실이 어디에 있어요?",
    "cn_sentence": "厕所在哪里？",
    "cn_pinyin": "Cè suǒ zài nǎ lǐ?",
    "theme": "facilities"
  },
  {
    "id": 195,
    "hanzi": "左边",
    "pinyin": "zuǒ biān",
    "meaning": "왼쪽",
    "kr": "왼쪽으로 도세요.",
    "cn_sentence": "请向左转。",
    "cn_pinyin": "Qǐng xiàng zuǒ biān zhuǎn.",
    "theme": "directions"
  },
  {
    "id": 196,
    "hanzi": "右边",
    "pinyin": "yòu biān",
    "meaning": "오른쪽",
    "kr": "오른쪽에 앉으세요.",
    "cn_sentence": "请坐在右边。",
    "cn_pinyin": "Qǐng zuò zài yòu biān.",
    "theme": "directions"
  }
];
